import type { DocModel, DocFileEntry, DocAnnotation } from "@invariance/gps-schemas";

/**
 * Render a DocModel to clean, shareable Markdown. Mirrors the `format.ts`
 * string-array pattern. The Markdown sibling of the HTML doc is what gets
 * committed/pasted where a browser isn't handy (PR descriptions, chat).
 */
export function renderDocMarkdown(model: DocModel): string {
  const L: string[] = [];
  L.push(`# ${model.title}`);
  if (model.subtitle) L.push(`*${model.subtitle}*`);
  L.push("");
  L.push(`_Generated by gps on ${model.generated_at}_`);
  L.push("");
  if (model.stats) {
    L.push(
      `**${model.stats.files_changed} files changed** · ` +
        `+${model.stats.added_lines}/-${model.stats.deleted_lines} · ` +
        `${model.stats.annotations} annotations · ` +
        `${model.stats.unannotated_hunks} unannotated hunks`,
    );
    L.push("");
  }

  // Prose / feature view first — the human narrative.
  for (const s of model.sections) {
    L.push(`## ${s.title}`);
    L.push("");
    L.push(s.markdown.trim());
    L.push("");
  }

  if (model.files.length) {
    L.push("## Changed files");
    L.push("");
    for (const f of model.files) {
      L.push(renderFile(f));
    }
  }

  if (model.annotations_unanchored.length) {
    L.push("## Other notes");
    L.push("");
    for (const a of model.annotations_unanchored) {
      L.push(`- ${annotationLabel(a)}`);
    }
    L.push("");
  }

  return L.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

function renderFile(f: DocFileEntry): string {
  const L: string[] = [];
  L.push(`### \`${f.path}\` — ${f.status}`);
  L.push("");

  if (f.binary) {
    L.push("_Binary file (not rendered)._");
    L.push("");
    return L.join("\n");
  }
  if (f.truncated) {
    L.push("_Large change — diff omitted. See the HTML doc for the full view._");
    L.push("");
  }

  // Annotations, sorted by line, as "lines X-Y: …" callouts.
  const sorted = [...f.annotations].sort((a, b) => a.start_line - b.start_line);
  if (sorted.length) {
    for (const a of sorted) {
      L.push(`> **lines ${range(a)}** — ${annotationLabel(a)}`);
    }
    L.push("");
  }

  if (!f.truncated && f.diff) {
    L.push("```diff");
    L.push(f.diff.trimEnd());
    L.push("```");
    L.push("");
  } else if (!f.truncated && f.after) {
    L.push("```");
    L.push(f.after.trimEnd());
    L.push("```");
    L.push("");
  }
  return L.join("\n");
}

function range(a: DocAnnotation): string {
  return a.start_line === a.end_line ? `${a.start_line}` : `${a.start_line}-${a.end_line}`;
}

function annotationLabel(a: DocAnnotation): string {
  const tag = a.kind === "llm" ? "" : ` _(${a.kind})_`;
  return `${a.text}${tag}`;
}
