#!/usr/bin/env tsx
/**
 * Generate `docs/guide/commands.md` by walking the Commander tree built in
 * `packages/cli/src/index.ts`. Run via `pnpm gen:docs`. CI re-runs this and
 * fails if the committed file drifts.
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { Command, Option } from "commander";
import { buildProgram } from "../packages/cli/src/index.js";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(HERE, "..", "docs", "guide", "commands.md");

function renderOption(opt: Option): string {
  const flags = opt.flags;
  const desc = opt.description || "";
  const dfl = opt.defaultValue !== undefined ? ` *(default: ${JSON.stringify(opt.defaultValue)})*` : "";
  return `- \`${flags}\` — ${desc}${dfl}`;
}

function renderCommand(cmd: Command, depth: number, parents: string[]): string[] {
  const out: string[] = [];
  const full = [...parents, cmd.name()].filter(Boolean).join(" ");
  if (depth > 0) {
    const heading = "#".repeat(Math.min(depth + 1, 6));
    out.push(`${heading} \`${full}\``);
    out.push("");
    const desc = cmd.description();
    if (desc) {
      out.push(desc);
      out.push("");
    }
    // Usage line — strip the Commander default "[options]" suffix noise.
    const usage = cmd.usage();
    if (usage) {
      out.push("```");
      out.push(`${full} ${usage}`.trim());
      out.push("```");
      out.push("");
    }
    // Options (skip the auto-injected --help)
    const opts = (cmd.options ?? []).filter((o: Option) => o.long !== "--help");
    if (opts.length) {
      out.push("**Options:**");
      out.push("");
      for (const o of opts) out.push(renderOption(o));
      out.push("");
    }
  }
  // Subcommands
  const subs = cmd.commands ?? [];
  for (const sub of subs) {
    if (sub.name() === "help") continue;
    out.push(...renderCommand(sub, depth + 1, [...parents, cmd.name()].filter(Boolean)));
  }
  return out;
}

async function main(): Promise<void> {
  const program = buildProgram();
  const lines: string[] = [
    "<!-- generated by scripts/gen-commands-doc.ts — do not edit by hand. Run `pnpm gen:docs`. -->",
    "",
    "# Command reference",
    "",
    "`gps` exposes its full surface as a CLI. Every read command supports `--json` (stable contract) and `--markdown` (LLM-optimal); ANSI colors auto-strip when piped.",
    "",
  ];
  // Group: print top-level subcommands alphabetically for stable diffs.
  const top = (program.commands ?? []).slice().sort((a, b) => a.name().localeCompare(b.name()));
  for (const sub of top) {
    if (sub.name() === "help") continue;
    lines.push(...renderCommand(sub, 1, []));
  }
  const body = lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
  await writeFile(OUT, body);
  console.log(`wrote ${path.relative(process.cwd(), OUT)} (${top.length} top-level commands)`);
}

main().catch((err: Error) => {
  console.error(err.stack ?? err.message);
  process.exit(1);
});
